---
id: 9943abc0-0c96-4168-9990-fe4111cfb09d
---

sequenceDiagram
    actor client as VueApp
    participant ws@{ "type" : "control" } as WebSocketHub
    participant db@{ "type" : "database" } as Db
    participant app as ASP.NET App
    participant fs@{ "type" : "control" } as FSharpModule
    participant rmd@{ "type" : "boundary" } as RemoteDevice

    client ->> app: Request Data
    app ->> db: Read Data
    app ->> client: Return Data
    client ->> ws: Establish Connection
    loop Device Listening
        rmd ->> fs: Device UDP Request
        fs ->> app: Call Handler Service
        app ->> db: Log Device Record
        app ->> ws: Trigger data update event
        ws ->> client: Send data
    end
    
    

